#!/bin/bash
cd "$1"
mkdir "GrupoR"
cp -r ".idea" "GrupoR"
cp "Inmobiliaria.iml" "GrupoR"
cp .gitignore "GrupoR"
cp "README.md" "GrupoR"
cp -r "src" "GrupoR"
zip -r "GrupoR.zip" "GrupoR"
rm -rf "GrupoR"
printf "Archivo 'GrupoR.tar' creado exitosamente.\n"